server:
  port: 8082
  address: localhost
spring:
  datasource:
    name: hikariDataSource
    pool-name: hikari
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.2/pitaka?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: pitaka01
    type: com.zaxxer.hikari.HikariDataSource
    maximum-pool-size: 5
    max-idle: 3
    max-wait: 10000
    min-idle: 2
    initial-size: 5
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 18800
# redis:
#            database: 0
#            host: 127.0.0.1
#            jedis:
#              pool:
#                #最大连接数据库连接数,设 0 为没有限制
#                max-active: 8
#                #最大等待连接中的数量,设 0 为没有限制
#                max-idle: 8
#                #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
#                max-wait: -1ms
#                #最小等待连接中的数量,设 0 为没有限制
#                min-idle: 0
#            lettuce:
#              pool:
#                max-active: 8
#                max-idle: 8
#                max-wait: -1ms
#                min-idle: 0
#              shutdown-timeout: 100ms
#            password: ''
#            port: 6379
mybatis:
  typeAliasesPackage: com.pitaka.www.mapper
  mapperLocations: classpath:mapper/*.xml
  configLocation: classpath:conf/mybatis-config.xml
logging:
  config: classpath:logback-boot.xml
